---
# Garage configuration with RPC secret
# IMPORTANT: Change the rpc_secret after first deployment!
apiVersion: v1
kind: Secret
metadata:
  name: garage-config
  namespace: garage
type: Opaque
stringData:
  garage.toml: |
    metadata_dir = "/data/meta"
    data_dir = "/data/data"
    db_engine = "sqlite"

    replication_mode = "none"

    compression_level = 1

    rpc_bind_addr = "[::]:3901"
    rpc_public_addr = "127.0.0.1:3901"
    rpc_secret = "6ff5dbeb1db3b0ecf03b006c9e16d3db09d923443110b59989e8a1bdd4130bb9"

    [s3_api]
    s3_region = "garage"
    api_bind_addr = "[::]:3900"
    root_domain = ".s3.garage.home"

    [s3_web]
    bind_addr = "[::]:3902"
    root_domain = ".web.garage.home"

    [admin]
    api_bind_addr = "[::]:3903"
