---
# MinIO root credentials
# IMPORTANT: Change these after first deployment!
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
type: Opaque
stringData:
  # Root user credentials (change these!)
  rootUser: "admin"
  rootPassword: "changeMe123!"
